const path = {
  home: "/",
  library: "/library",
  login: "/login",

  student: "/student",
  studentProfile: "/student/profile",
  studentMeetings: "/student/meetings",
  studentProgress: "/student/progress",
  studentPrograms: "/student/programs",
  //studentMeet: "/student/meet",
  studentProgramDetail: "/student/programs/:programId",
  studentProgramCompetencies: "/student/programs/:programId/competencies",
  studentMyProgram: "/student/my-program",
  studentMyProgramDetail: "/student/my-program/:programId",
  studentSessions: "/student/sessions/:programId",
  studentProgramDetailView: "/student/program-detail/:programId",
  studentProgramList: "/student/program-list",
  studentProgramMeet: "/student/meet/:programId",
  studentCompetence: "/student/competence/:programId",

  tutor: "/tutor",
  tutorProfile: "/tutor/profile",
  tutorCalendar: "/tutor/calendar",
  tutorProgress: "/tutor/progress",
  tutorPrograms: "/tutor/programs",
  //tutorMeet: "/tutor/meet",
  tutorProgramDetail: "/tutor/programs/:programId",
  tutorProgramCompetencies: "/tutor/programs/:programId/competencies",
  tutorMyProgram: "/tutor/my-program",
  tutorMyProgramDetail: "/tutor/my-program/:programId",
  tutorSessions: "/tutor/sessions/:programId",
  tutorProgramMeet: "/tutor/meet/:programId",
  tutorCompetence: "/tutor/competence/:programId",
  tutorLibrary: "/tutor/library",
  tutorProgramList: "/tutor/program-list",
  tutorProgramDetailView: "/tutor/program-detail/:programId",

  admin: "/admin",
  adminProfile: "/admin/profile",
  adminWelcome: "/admin/home",
  adminPrograms: "/admin/programs",
  adminTutors: "/admin/tutors",
  adminMentees: "/admin/mentees",
  adminStudents: "/admin/students",
  adminData: "/admin/data",
} as const;

export default path;
